# Required Metadata
sonar.projectKey=roboshop:catalogue
sonar.projectName=roboshop-catalogue



# Code Paths
sonar.sources=.
8

# Exclusions
sonar.exclusions=**/node_modules/**,**/*.spec.js,Jenkinsfile,Dockerfile